# This workflow will generate user script using yarn and then publish to GitHub repo

name: build and push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: actions/setup-node@v3
        with:
          node-version: 16
        run: |
          yarn
          yarn build src/MyNovelReader
      - name: push
        uses: actions/checkout@v3
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
