# This workflow will generate user script using yarn and then publish to GitHub repo

name: User script generation

on: [push]
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build prepare
        run: |
          yarn install
      - name: build
        run: |
          yarn build src/MyNovelReader
      - name: convert EOL
        run: |
          sed -i 's/\r//g' scripts/MyNovelReader.user.js
      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add scripts
          git commit -m "auto: user script generated"
          git push
