name: Build userscript

on:
  pull_request_target:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: build
        run: |
          yarn
          yarn build src/MyNovelReader
      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add scripts
          version=$(grep -oP "(?<=// @version        ).*" scripts/MyNovelReader.user.js)
          git commit -m "ci: build userscript version $version"
          git push
